// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyhchpxfyoxqkthecnyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5aGNocHhmeW94cWt0aGVjbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDA0MjcsImV4cCI6MjA2Mjg3NjQyN30.xdJW82Y_CB_mzCx_vUFLxM-0JWlCaOrn2IYLboYbUr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
